### ISSUE TITLE
Incorrect capitalization of true in CurieIMU documentation

### ISSUE THREAD

**Issue by per1234** [arduino/ArduinoCore-arc32#584]
The Boolean literal `true` is incorrectly capitalized "True" in the following reference pages:
- https://www.arduino.cc/en/Reference/CurieIMUgetInterruptStatus
- https://www.arduino.cc/en/Reference/CurieIMUmotionDetected
- https://www.arduino.cc/en/Reference/CurieIMUshockDetected
- https://www.arduino.cc/en/Reference/CurieIMUstepsDetected
- https://www.arduino.cc/en/Reference/CurieIMUtapDetected

**Comment by facchinm** [comment]
@kengdahl can you take a look?

**Comment by kengdahl** [comment]
@facchinm Sure.

**Comment by kengdahl** [comment]
Done
