### ISSUE TITLE
some EEPROM.CPP ERROR

### ISSUE THREAD

**Issue by naumann** [arduino/ArduinoCore-arc32#586]
Hi!

the library works perfectly, my code also, but just #include <ESP_EEPROM.h> and the error as below:
OBS: with EEPROM library works too, but I need long words.
thank you in advance!
André Naumann

Arduino: 1.8.5 (Windows Store 1.8.10.0) (Windows 10), Placa:"WeMos D1 R1, 80 MHz, 4M (1M SPIFFS), v2 Lower Memory, Disabled, TLS_MEM, Only Sketch, 921600"

Archiving built core (caching) in: C:\Users\ANDR~1\AppData\Local\Temp\arduino_cache_122390\core\core_esp8266_esp8266_d1_CpuFrequency_80,FlashSize_4M1M,LwIPVariant_v2mss536,Debug_Disabled,DebugLevel_TLS_MEM,FlashErase_none,UploadSpeed_921600_1699067254c2d66b8d7fd6e446310dad.a
libraries\EEPROM\EEPROM.cpp.o: In function `EEPROMClass::getConstDataPtr() const':

C:\Users\André\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.1\libraries\EEPROM/EEPROM.cpp:39: multiple definition of `EEPROMClass::EEPROMClass(unsigned int)'

libraries\ESP_EEPROM\ESP_EEPROM.cpp.o:C:\Users\André\Documents\Arduino\libraries\ESP_EEPROM\src/ESP_EEPROM.cpp:110: first defined here

libraries\EEPROM\EEPROM.cpp.o: In function `EEPROMClass::getConstDataPtr() const':

C:\Users\André\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.1\libraries\EEPROM/EEPROM.cpp:39: multiple definition of `EEPROMClass::EEPROMClass(unsigned int)'

libraries\ESP_EEPROM\ESP_EEPROM.cpp.o:C:\Users\André\Documents\Arduino\libraries\ESP_EEPROM\src/ESP_EEPROM.cpp:110: first defined here

libraries\EEPROM\EEPROM.cpp.o: In function `EEPROMClass::EEPROMClass()':

C:\Users\André\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.1\libraries\EEPROM/EEPROM.cpp:44: multiple definition of `EEPROMClass::EEPROMClass()'

libraries\ESP_EEPROM\ESP_EEPROM.cpp.o:C:\Users\André\Documents\Arduino\libraries\ESP_EEPROM\src/ESP_EEPROM.cpp:134: first defined here

libraries\EEPROM\EEPROM.cpp.o: In function `EEPROMClass::EEPROMClass()':

C:\Users\André\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.1\libraries\EEPROM/EEPROM.cpp:44: multiple definition of `EEPROMClass::EEPROMClass()'

libraries\ESP_EEPROM\ESP_EEPROM.cpp.o:C:\Users\André\Documents\Arduino\libraries\ESP_EEPROM\src/ESP_EEPROM.cpp:134: first defined here

libraries\EEPROM\EEPROM.cpp.o: In function `EEPROMClass::commit()':

C:\Users\André\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.1\libraries\EEPROM/EEPROM.cpp:51: multiple definition of `EEPROMClass::begin(unsigned int)'

libraries\ESP_EEPROM\ESP_EEPROM.cpp.o:C:\Users\André\Documents\Arduino\libraries\ESP_EEPROM\src/ESP_EEPROM.cpp:159: first defined here

libraries\EEPROM\EEPROM.cpp.o: In function `EEPROMClass::read(int)':

C:\Users\André\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.1\libraries\EEPROM/EEPROM.cpp:90: multiple definition of `EEPROMClass::read(int)'

libraries\ESP_EEPROM\ESP_EEPROM.cpp.o:C:\Users\André\Documents\Arduino\libraries\ESP_EEPROM\src/ESP_EEPROM.cpp:277: first defined here

libraries\EEPROM\EEPROM.cpp.o: In function `EEPROMClass::write(int, unsigned char)':

C:\Users\André\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.1\libraries\EEPROM/EEPROM.cpp:99: multiple definition of `EEPROMClass::write(int, unsigned char)'

libraries\ESP_EEPROM\ESP_EEPROM.cpp.o:C:\Users\André\Documents\Arduino\libraries\ESP_EEPROM\src/ESP_EEPROM.cpp:296: first defined here

libraries\EEPROM\EEPROM.cpp.o: In function `EEPROMClass::commit()':

C:\Users\André\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.1\libraries\EEPROM/EEPROM.cpp:114: multiple definition of `EEPROMClass::commit()'

libraries\ESP_EEPROM\ESP_EEPROM.cpp.o:C:\Users\André\Documents\Arduino\libraries\ESP_EEPROM\src/ESP_EEPROM.cpp:339: first defined here

libraries\EEPROM\EEPROM.cpp.o: In function `EEPROMClass::end()':

C:\Users\André\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.1\libraries\EEPROM/EEPROM.cpp:76: multiple definition of `EEPROMClass::end()'

libraries\ESP_EEPROM\ESP_EEPROM.cpp.o:C:\Users\André\Documents\Arduino\libraries\ESP_EEPROM\src/ESP_EEPROM.cpp:248: first defined here

libraries\EEPROM\EEPROM.cpp.o: In function `EEPROMClass::getConstDataPtr() const':

C:\Users\André\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.1\libraries\EEPROM/EEPROM.cpp:39: multiple definition of `EEPROM'

libraries\ESP_EEPROM\ESP_EEPROM.cpp.o:C:\Users\André\Documents\Arduino\libraries\ESP_EEPROM\src/ESP_EEPROM.cpp:110: first defined here

c:/users/andré/documents/arduinodata/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: Warning: size of symbol `EEPROM' changed from 24 in libraries\ESP_EEPROM\ESP_EEPROM.cpp.o to 16 in libraries\EEPROM\EEPROM.cpp.o

collect2.exe: error: ld returned 1 exit status

exit status 1
Erro compilando para a placa WeMos D1 R1

Este relatório teria mais informações com
"Mostrar a saida detalhada durante a compilação"
opção pode ser ativada em "Arquivo -> Preferências"

**Comment by facchinm** [comment]
Hi @naumann ,
I think you are posting to the wrong repository :slightly_smiling_face: The correct one is https://github.com/esp8266/Arduino . Thanks!
